# Generated by Django 5.2.1 on 2026-01-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='hierarchy_order',
            field=models.IntegerField(default=0, verbose_name='Ordem na Hierarquia'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='collaborators.collaborator', verbose_name='Gestor/Líder'),
        ),
    ]
