# Generated by Django 5.2.1 on 2026-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_collaborator_hierarchy_order_collaborator_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='hierarchy_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Ordem na Hierarquia'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
    ]
