# Generated by Django 5.2.1 on 2026-01-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0008_orgchart_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgchartNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(blank=True, default="", verbose_name="Texto")),
                ("x", models.IntegerField(verbose_name="Posicao X")),
                ("y", models.IntegerField(verbose_name="Posicao Y")),
                ("width", models.IntegerField(blank=True, null=True, verbose_name="Largura")),
                ("height", models.IntegerField(blank=True, null=True, verbose_name="Altura")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgchart_notes",
                        to="departments.department",
                        verbose_name="Setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota do organograma",
                "verbose_name_plural": "Notas do organograma",
            },
        ),
    ]
