# Generated by Django 4.2.23 on 2026-02-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0009_orgchart_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgchartnote',
            name='department',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='hierarchy_order',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='leadership_role',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='orgchart_source_handle',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='orgchart_target_handle',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='orgchart_x',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='orgchart_y',
        ),
        migrations.DeleteModel(
            name='OrgchartEdge',
        ),
        migrations.DeleteModel(
            name='OrgchartNote',
        ),
    ]
