# Generated by Django 5.2.8 on 2025-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('repo_url', models.URLField(blank=True, null=True, verbose_name='Repositório')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('readme', models.FileField(blank=True, null=True, upload_to='projects/readmes/', verbose_name='Readme (.md)')),
                ('doc_changed_at', models.DateField(blank=True, null=True, verbose_name='Data de Alteração de Documentação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
