# Generated by Django 5.2.8 on 2025-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Admin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Principal'),
        ),
    ]
