# Generated by Django 5.2.8 on 2025-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0002_project_admin_url_alter_project_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ports',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portas'),
        ),
    ]
