# Generated by Django 5.2.8 on 2025-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0003_project_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credential_user',
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                verbose_name='Usuário (credencial)',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='credential_password',
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                verbose_name='Senha (credencial)',
            ),
        ),
    ]

