# Generated by Django 5.2.1 on 2026-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
        ('departments', '0001_initial'),
        ('projectsmanager', '0004_project_credential_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsible_collaborators',
            field=models.ManyToManyField(blank=True, related_name='responsible_for_projects', to='collaborators.collaborator', verbose_name='Colaboradores Responsáveis'),
        ),
        migrations.AddField(
            model_name='project',
            name='used_by_departments',
            field=models.ManyToManyField(blank=True, related_name='projects_used', to='departments.department', verbose_name='Setores que Utilizam'),
        ),
    ]
