# Generated by Django 5.2.1 on 2026-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0005_project_responsible_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Status Online'),
        ),
    ]
