# Generated by Django 4.2.23 on 2026-02-11 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectsmanager', '0009_alter_project_status_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, help_text='Permite que o usuário veja este projeto na Central de Acessos', verbose_name='Pode Visualizar')),
                ('can_edit', models.BooleanField(default=False, help_text='Permite que o usuário edite este projeto', verbose_name='Pode Editar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='projectsmanager.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso de Usuário a Projeto',
                'verbose_name_plural': 'Acessos de Usuários a Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userprojectaccess',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_access'),
        ),
    ]
