# Generated by Django 4.2.23 on 2026-02-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0010_userprojectaccess_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprojectaccess',
            name='unique_user_project_access',
        ),
        migrations.RemoveField(
            model_name='userprojectaccess',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectaccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessCenter',
        ),
        migrations.DeleteModel(
            name='UserProjectAccess',
        ),
    ]
