# Generated by Django 4.2.23 on 2026-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao'),
        ),
    ]
