# Generated by Django 4.2.23 on 2026-02-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_department_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentAccess',
        ),
    ]
