# Generated by Django 5.2.1 on 2026-01-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Subtarefa', 'verbose_name_plural': 'Subtarefas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída Em'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'A Fazer'), ('IN_PROGRESS', 'Em Progresso'), ('IN_REVIEW', 'Em Revisão'), ('DONE', 'Concluída')], db_index=True, default='TODO', max_length=20, verbose_name='Status'),
        ),
    ]
